### ISSUE TITLE
Text to Speech for hint

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#101]
As an AnyMemo user, I would like to have the text to speech option for the hint.

Tasks:
1. Create DB field for hintAudio in Settings table
2. Add hintTTS field in the card utility for TTS 
3. Update the UI files that manipulate TTS for question, answer, and hint
4. Write tests

Risk: Low
Priority: Low

Story points: 3

Story points is 3 because this feature already exists for question and answer. We do not need to figure out how to do text to speech. We only need to figure out how to add it to the new hint field.

![image](https://user-images.githubusercontent.com/25259429/38395125-6ab5ec4e-38ff-11e8-8e97-af9ea7bf0ea2.png)

[Unit Test](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/SettingTest.java)

**Comment by mukulikadey** [comment]
Acceptance Test: PASSED
![image](https://user-images.githubusercontent.com/25259429/38390919-bab03402-38f0-11e8-87ca-794870c67fc8.png)

**Comment by mukulikadey** [comment]
Hour(s): 5

**Comment by coreylevine** [comment]
Final Mockups:
![image](https://user-images.githubusercontent.com/25109164/38706917-0e8a6b2e-3e7d-11e8-9814-d6ca9651e2a1.png)
![image](https://user-images.githubusercontent.com/25109164/38706974-485e5cde-3e7d-11e8-9cd5-446f94465c65.png)

**Comment by mukulikadey** [comment]
UNIT TESTS:
https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/SettingTest.java

**Comment by guipadua** [comment]
Demoed and it works. Tests just for the library used for the text to speech.
