### ISSUE TITLE
Favourites Overview

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#103]
As an AnyMemo user, when I look at the card list, I would like my favourite cards to be highlighted.

Tasks:
- [x] Highlight favorite cards -> updated to a star on that row. 
- [x] Disabling ability to favourite and unfavourite cards in the favourite deck & quiz
- [x] Espresso tests

Risk: Low
Priority: Low

Story points: 3

This feature is 3 story points because it is an enhancement to a pre-existing feature. The logic for the database field for favourite has already been added.

**Comment by j-suguma** [comment]
![image](https://user-images.githubusercontent.com/25251601/38167929-5c9190e6-350d-11e8-8924-1dbaea7454b4.png)

**Comment by svelupillai** [comment]
When a card is a 'favourite', in the card list overview it will be highlighted pink as shown below:
![image](https://user-images.githubusercontent.com/25239116/38177484-7a882d26-35d0-11e8-9fb3-c14a56b52432.png)

**Comment by mukulikadey** [comment]
Virtual Release Video: Favorites Overview 

[FavOverview.zip](https://github.com/jameelbrochu/AnyMemo/files/1866770/FavOverview.zip)

**Comment by guipadua** [comment]
Based on the video looks fine. A star would be more obvious as a favorite indicator than the row color highlighting. I saw acceptance and espresso tests on this one.

**Comment by svelupillai** [comment]
When we made mockups we thought highlighting the row pink would be clear. We will consider the star as a potential enhancement!

**Comment by svelupillai** [comment]
After speaking with Gui, we have decided to put a star next to the question/answer instead of highlighting the row.

**Comment by svelupillai** [comment]
Hours: 5

**Comment by rekandiah** [comment]
Espresso Test:
https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/FavouriteOverviewTest.java
