### ISSUE TITLE
Multiple Choice Questions

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#104]
As an AnyMemo user, I would like to have a deck of multiple choice questions.

Tasks:
1. Create mockups for UI pages for multiple choice questions feature. (Task: #118)
2. Create Database logic: Entity +DAO implementation. (Task: #116)
3. Add MC checkbox and Implement behavior of checkbox (Task: #119)
4. Modify layout of multiple choice decks shown on recent list page such that user can identify it as MC deck. (Task: #120 )
5. Create study activity for MC (Task: #121)
6. Implement behaviour of study activity for MC (Task: #117)
7. Write espresso tests for edit and study MC (Task: #122)
8. Create List View of Cards (Task: #129)

Acceptance criteria:

Risk: Low
Priority: Medium

Story points: 13

Story points is 13 because we need to change the card entity to accommodate for multiple choice questions. As well, we need to check if the user has chosen the correct answer. If they haven't, then we need to display the correct answer. We also need to create two new activities one for adding new cards and one for the study mc activity.

**Comment by j-suguma** [comment]
![image](https://user-images.githubusercontent.com/25251601/38167923-4b21d172-350d-11e8-9a94-0cfa73998904.png)

**Comment by mukulikadey** [comment]
Updated Acceptance Tests: PASSED 

![image](https://user-images.githubusercontent.com/25259429/38175481-f3eafb4c-35aa-11e8-88a5-29eb6b344288.png)

**Comment by coreylevine** [comment]
Final Mockup:
![37859963-b3a2bbba-2ef2-11e8-887d-fbfad228c6f9](https://user-images.githubusercontent.com/25109164/38177219-7f95779c-35cb-11e8-9307-e731dc079bbf.jpg)

**Comment by mukulikadey** [comment]
Virtual Release Video: Multiple Choice Deck 

[MultipleChoice.zip](https://github.com/jameelbrochu/AnyMemo/files/1866767/MultipleChoice.zip)

**Comment by mukulikadey** [comment]
Class diagram: https://github.com/jameelbrochu/AnyMemo/wiki/Class-Diagram

**Comment by guipadua** [comment]
Nice one. Just a thought, can one create the DBs on Google Docs for example and then load from there? That would be cool.
I saw few tests, this story probably can have many tests and edge cases?

**Comment by mukulikadey** [comment]
@guipadua Currently we do not have the functionality of creating and loading DBs from Google Docs. And as for the tests, we will be writing more this sprint.

**Comment by rekandiah** [comment]
Espresso Tests: https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/MC_AnswerNotSelected.java

https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/MC_Study.java

Unit Tests:

https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/MultipleChoiceCardDaoTest.java
