### ISSUE TITLE
Enhance the detailed results page to review quiz

### ISSUE THREAD

**Issue by mukulikadey** [jameelbrochu/AnyMemo#105]
As an AnyMemo user, after having completed my quiz, I would like to view the correct questions in green and the incorrect questions in red, in the order by ID. 

Tasks:
- Create mockup for enhanced quiz results page (#148)
- Modify Quiz Review activity with enhancements (#149)

Acceptance criteria:
1. Code has been reviewed by two people.
2. All tests pass.
3. Quality assurance has been preformed.

Risk: Low
Priority: Low

Story points: 3

This user story is worth three points because we had already implemented the RecyclerView for the multiple choice preview/edit activity so it did not require much learning to also implement it for the quiz review page. It did require that we combine both ArrayLists that we were using to hold the forgotten and remembered cards into a new ArrayList.

![image](https://user-images.githubusercontent.com/25259429/38702711-4a60e0be-3e6f-11e8-92c7-39692f8709da.png)

**Comment by mukulikadey** [comment]
Acceptance Tests: PASSED

![image](https://user-images.githubusercontent.com/25259429/38705530-d21d3d06-3e77-11e8-9cb5-d6ffeb01b4cb.png)

**Comment by coreylevine** [comment]
Final Mockups:
![image](https://user-images.githubusercontent.com/25109164/38707000-68f9bd12-3e7d-11e8-8f9f-a985fb06b154.png)
![image](https://user-images.githubusercontent.com/25109164/38707005-701508e0-3e7d-11e8-8453-7fb1da95c70b.png)
![image](https://user-images.githubusercontent.com/25109164/38707013-7747d64c-3e7d-11e8-937f-b2d53b0ba342.png)

**Comment by guipadua** [comment]
Demoed, it works. Manual tests being done according to PR policy.
