### ISSUE TITLE
Write acceptance tests for new features

### ISSUE THREAD

**Issue by mukulikadey** [jameelbrochu/AnyMemo#115]
Write acceptance tests for:
[User Story 103](https://github.com/jameelbrochu/AnyMemo/issues/103)
[User Story 104](https://github.com/jameelbrochu/AnyMemo/issues/104)
[Acceptance Tests](https://docs.google.com/spreadsheets/d/159-RxAREY8DVwjwsrFlrm-Jh_xOtLmEBqAoSX1JAdYg/edit#gid=0)

**Comment by j-suguma** [comment]
Hours spent: 1
