### ISSUE TITLE
Create mockups for UI pages for multiple choice questions feature.

### ISSUE THREAD

**Issue by jameelbrochu** [jameelbrochu/AnyMemo#118]
User story: #104

Create mockups of UI design pages for the new multiple choice questions feature.
Ideal Hour(s): 30 mins

**Comment by jameelbrochu** [comment]
![aa7102dc-a767-4526-a877-cbb64543dede](https://user-images.githubusercontent.com/16848284/37859672-b731b088-2eed-11e8-8639-e3c7eeb8b986.jpeg)

**Comment by mukulikadey** [comment]
![image](https://user-images.githubusercontent.com/25259429/37859671-b677f576-2eed-11e8-93d8-a9f8f6a5c066.png)

Simple flow of how i think the functionality should flow

**Comment by mukulikadey** [comment]
@rekandiah I like the overall flow of your mockup. Super detailed. I especially like step 6 where we display the "type of deck"; it'll clear confusions for the user so i definitely think we should include that. 

@jameelbrochu I really like the way you displayed the question/answer to the user after they've made a selection. I think the radio buttons in the question and answer place is a good idea, however I am still not sure about having two radio buttons at the beginning when creating the deck. I feel like the checkbox at the beginning will make it easier.

**Comment by jameelbrochu** [comment]
I agree, it's very important that we clearly display the two types of decks for the user. I think for now, we should go with the checkbox since it is easier to implement and then later if we feel the need to enhance the create new DB screen, we can change it to a radio type.

**Comment by rekandiah** [comment]
@jameelbrochu I like your idea of having a submit button and then showing the answers! But I would still prefer having a checkbox when creating a deck.

@mukulikadey happy we thought of the same flow of logic! haha!

**Comment by rekandiah** [comment]
Here's our final mockup. The ending steps will now have a submit button before displaying the answer.
![mockup](https://user-images.githubusercontent.com/15826622/37859963-b3a2bbba-2ef2-11e8-887d-fbfad228c6f9.jpg)

**Comment by mukulikadey** [comment]
After thorough discussions, some UI changes were made throughout the development of this feature, and so here is the final mockup for the Multiple Choice Functionality: 

![image](https://user-images.githubusercontent.com/25259429/38175500-562df4d0-35ab-11e8-9554-b9b841671345.png)

**Comment by rekandiah** [comment]
nb of hours: 1/2 hour
