### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#134]
As an AnyMemo developer, I would like to have a Static Analysis tool run on Jenkins after each successful build.

Risk: Low
Priority: High
Story Points: 3
Ideal Hour(s): 6

![image](https://user-images.githubusercontent.com/25259429/38395096-4514d7b6-38ff-11e8-93f9-ba9d18a71911.png)

This user story is worth three points since research had to be done to understand and integrate a gradle task for running the static analysis tool. In addition jenkins had to be configured to display the results of the analysis and run the plugin. Compared to the splitting the build from the tests, this story involved more work.

**Comment by j-suguma** [comment]
Hours spent: 7

**Comment by j-suguma** [comment]
![image](https://user-images.githubusercontent.com/25251601/38701069-ef9cd114-3e6a-11e8-8b93-b04f9acaa668.png)

**Comment by j-suguma** [comment]
Example of how it looks
![image](https://user-images.githubusercontent.com/25251601/38707066-bfb73e40-3e7d-11e8-8cb2-779f4db46af8.png)

**Comment by guipadua** [comment]
Added FindBugs and manually adding results on each PR. Besides that, adding detailed PDF of the problems on the PR.
