### ISSUE TITLE
Modify and Delete a multiple choice card

### ISSUE THREAD

**Issue by jameelbrochu** [jameelbrochu/AnyMemo#136]
As an AnyMemo user, I should be able to modify/delete a multiple choice card and delete a multiple choice deck.

Tasks: 
1. Delete a Multiple Choice Card and Deck( #139)
2. Modify a Multiple Choice Card ( #140) 

Acceptance Criteria:
1. Code has been reviewed by two people.
2. All tests pass.
3. Quality assurance has been preformed.

Risk: Low
Priority: medium

Story points: 5

5 story points because need to add two functionalities to the mc card that requires adding sqlite functions, dao functions and modifies the activities involved. Also have to do espresso and unit tests.

[Unit Tests](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/MultipleChoiceCardDaoTest.java)
[Espresso Tests](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/MC_EditCard.java)
![at](https://user-images.githubusercontent.com/15826622/38403735-94e4f616-3933-11e8-8087-7b1fb6f02556.PNG)

**Comment by mukulikadey** [comment]
UNIT TESTS: 
https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/MultipleChoiceCardDaoTest.java 

ESPRESSO TESTS:
https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/MC_EditCard.java

**Comment by guipadua** [comment]
Demoed, it works. It automatically chooses the last one as default if the user didn't select anything. This was also added to the random function. Has different types of tests.
