### ISSUE TITLE
Fix the bug that the header does not show up on the preview/edit screen of the multiple choice deck.

### ISSUE THREAD

**Issue by jameelbrochu** [jameelbrochu/AnyMemo#137]
User Story: #104

Actual:

1. Navigate to Recent List Fragment
2. Click on "More" next to a MC deck
3. List of cards is displayed

Expected:

1. Navigate to Recent List Fragment
2. Click on "More" next to a MC deck
3. List of cards is displayed with header on top

**Comment by coreylevine** [comment]
Visual enhancement, not a bug. We decided not to implement this enhancement this sprint.

**Comment by jameelbrochu** [comment]
In the end, was able to fix the issue.
