### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#144]
User Story: #82

Create mockups for the UI for the history page.

We would like to have:
- List of attempt and quiz mark
- The user's quiz average

Hours 0.5

**Comment by j-suguma** [comment]
Mockup: When the user click the more button on the deck, it open up the options fragment and when they click quiz history itll open up the quiz history activity
![30221631_2042725952434983_4468349533692100608_o](https://user-images.githubusercontent.com/25251601/38387349-7d37ccbc-38e5-11e8-8859-d21cf78beac3.jpg)

**Comment by coreylevine** [comment]
We should put the Quiz History below Quiz

**Comment by j-suguma** [comment]
Okay sounds good!

**Comment by j-suguma** [comment]
![shuffle mockup - page 1 1](https://user-images.githubusercontent.com/25251601/38393352-859fd76a-38f8-11e8-87ea-eb8967a1b5be.png)
