### ISSUE TITLE
Enable shuffling of cards in a deck

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#19]
As an AnyMemo user, I would like to be able to shuffle the deck of flash cards that I am using.

Tasks

1. Corey create mockup and explanation (Task #41)
2. Senaga create mockup and explanation (Task #42)
3. Mukulika create mockup and explanation (Task #44)
4. Regina create mockup and explanation (Task #45)
5. Jameel create mockup and explanation (Task #47)
6. Jonathan create mockup and explanation (Task #48)
7. Add a button to shuffle cards. (Task #21)
8. Understand the underlying structure of how cards are organized in a deck, and which classes are involved. (Task #22)
9. Implement the backed logic for shuffling the deck. (Task #23)
10. Connect the frontend and backend. (Task #24)
11. Write tests. (Task #25)

Acceptance criteria:

- Code has been reviewed by someone other than the developer.
- All tests pass.
- Quality assurance has been preformed.

Risk: Low
Value: High
Story points: 5

**Comment by mukulikadey** [comment]
![shuffle mockup - page 1 2](https://user-images.githubusercontent.com/25251601/35769477-82d1a9e0-08d9-11e8-8771-90a675d7cc90.jpeg)

**Comment by guipadua** [comment]
Shuffle work by shuffling before getting into learning mode. It also has unshuffle back to original.
