### ISSUE TITLE
Ability to mark a card as favorite

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#20]
As an AnyMemo user, I would like to be able to mark a card as a favorite so that I will be able to easily access it later.

Tasks:

1. Create mockups. (Task #31)
2. Add a favorite button on each card. (Task #27)
3. Create database field 'favourite' for Cards to be able to write to it. (#99)
4. Create a new database for the favourite cards. (Task #28)
5. Display the favorite deck in the frontend. (Task #30)
6.  Unfavorite a card  - remove from the favourites deck. (Task #29)

Acceptance criteria:

- Code has been reviewed by two people.
- All tests pass.
- Quality assurance has been preformed.

Risk: Low
Priority: High
Story points: 13

Acceptance Tests:
![favorite](https://user-images.githubusercontent.com/15826622/37178705-4a2dd5a0-22f1-11e8-81a4-80ec354034a8.PNG)

This story is 13 points because we need to create a new database to store the favourites deck. Each deck is a new database and so we need to figure out how to create a new database, and then add items from a different database to it.

**Comment by coreylevine** [comment]
Demo video for Sprint 4 virtual release meeting:
https://drive.google.com/open?id=1G9qAbW5_io9ak7pQIhHTn387AME54CD9

**Comment by mukulikadey** [comment]
![image](https://user-images.githubusercontent.com/25259429/37574877-46118c4e-2afa-11e8-8fd3-029e6f437b00.png)

Acceptance Test

**Comment by guipadua** [comment]
Based on the video looks good.
