### ISSUE TITLE
Add button to shuffle cards

### ISSUE THREAD

**Issue by svelupillai** [jameelbrochu/AnyMemo#21]
User Story: #19

Add a button on the UI that allows users to click to shuffle cards.  

1. Find a shuffle icon.
2. Add the shuffle icon to the homepage, between the name of the deck and "MORE".
3. Move the search icon into the three dots menu.
4. Add a shuffle button in the header, between the edit button and the three dots menu.

**Comment by j-suguma** [comment]
![shuffle mockup - page 1 1](https://user-images.githubusercontent.com/25251601/35769420-8a3cdea8-08d8-11e8-8b7d-db7a07bd784a.jpeg)
So this is the mock-up I created! Let me know what you guys think

**Comment by svelupillai** [comment]
Looks great! Exactly what we had discussed on Thursday.

**Comment by coreylevine** [comment]
This looks perfect! Should we maybe just label what the other two pages are called, so that we can refer to them in discussions later on?

**Comment by j-suguma** [comment]
![shuffle mockup - page 1 2](https://user-images.githubusercontent.com/25251601/35769477-82d1a9e0-08d9-11e8-8771-90a675d7cc90.jpeg)
Added!

**Comment by coreylevine** [comment]
Perfect!
