### ISSUE TITLE
Understand the structure that cards are organized.

### ISSUE THREAD

**Issue by svelupillai** [jameelbrochu/AnyMemo#22]
User Story: #19 

In order to enable shuffle mode, the structure in which the cards are stored in must be understood. The key classes involved need to be identified and thoroughly understood, to make the necessary changes.

Estimated Hour(s): 4

**Comment by j-suguma** [comment]
I believe i have an understanding about how the cards are organized. Attached you'll find my notes which may be messy but I'll explain in person
[AM Card Ordering.txt](https://github.com/jameelbrochu/AnyMemo/files/1695195/AM.Card.Ordering.txt)
