### ISSUE TITLE
Hint mode

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#26]
As an AnyMemo user, I would like to have a hint mode for when I do not know the answer to a flash card question.

Tasks:

1. Create a field so that the user can add a hint from the user interface. (Task #33)
2. Create mockup of UI (Task #77)
3. Create an attribute in the database to store the hint. (Task #34)
4. Update the backend to accommodate the new attribute to add the new hint attribute. (Task #35)
5. Update the backend to retrieve a hint from the database (Task #76 )
6. Connect the frontend and the backend. (Task #36)
7. Write tests. (Task #37)

Acceptance criteria:

- Code has been reviewed by someone other than the developer.
- All tests pass.
- Quality assurance has been preformed.

Risk: Low
Value: High
Story points: 8

**Comment by guipadua** [comment]
Works, have unit test for get/setters, but can have some more. Maybe espresso tests. And some potential enhancements can be added: turn it on and off, etc.
