### ISSUE TITLE
Setup testing environment

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#3]
As developer, I should have a continuous integration environment setup that complies the code and runs the tests with every commit.

Tasks:
1. Find a suitable continuous integration. (Task: #6)
2. Integrate the continuous integration with AnyMemo application. (Task: #7)

Acceptance criteria:
- A continuous integration environment is running.

Risk: High
Value: High
Story points: 8

**Comment by guipadua** [comment]
Works on Jenkins locally with Emulator. It generates reports. It has all the dummy tests per person.
