### ISSUE TITLE
Display the favorite deck

### ISSUE THREAD

**Issue by svelupillai** [jameelbrochu/AnyMemo#30]
User Story: #20 

The UI will fetch the favorite deck and give users the option to choose to see the deck.

Ideal Hours: 4

**Comment by j-suguma** [comment]
Hey guys so I added the Favorites Deck button to the Misc tab. For some reason when I tried to put it on the main nav bar the app would always crash. Let me know what you think! @svelupillai @coreylevine 
![28958720_2004448706262708_3532202561887010816_o](https://user-images.githubusercontent.com/25251601/37243319-68f260dc-2445-11e8-9475-bdb23b7a622e.png)
