### ISSUE TITLE
Create mockups for favourites feature

### ISSUE THREAD

**Issue by svelupillai** [jameelbrochu/AnyMemo#31]
User Story: #20 

Create mockups for how the UI should look for adding favourites to a deck, removing favourites, and the favourites deck itself.

Ideal Hour(s): 3

**Comment by svelupillai** [comment]
Below is how the card would look like if the card was not a favourite:
<img width="198" alt="heart" src="https://user-images.githubusercontent.com/25239116/37172708-90384984-22df-11e8-996f-dbe0b61657cf.PNG">
Below is what the card would look like once the user would like to favourite it:
<img width="200" alt="hearted" src="https://user-images.githubusercontent.com/25239116/37172756-b7c657ca-22df-11e8-96f7-9ca768f5fb30.PNG">

**Comment by coreylevine** [comment]
![image](https://user-images.githubusercontent.com/25109164/37176233-c0a7f7fe-22e9-11e8-8e72-46c454e180a1.png)

**Comment by j-suguma** [comment]
I agree with the icon's though i guess either heart or a star works!

**Comment by coreylevine** [comment]
Do you guys think we should put a new icon on the landing page menu bar for the favorites deck and then when you click on that icon the application is launched?

**Comment by svelupillai** [comment]
yes we should, sounds feasible and clear

**Comment by j-suguma** [comment]
This is the final mockup I came up with:
![shuffle mockup - page 7](https://user-images.githubusercontent.com/25251601/37242741-8020610e-243c-11e8-9b0c-0838c2571136.png)

I changed the displaying of the favorite deck from the navbar to the recent age. However during implementation whatever works better we'll go with that!

**Comment by j-suguma** [comment]
Also here is the interactive prototype:
https://invis.io/WNFWQVQFDQ9
Click on countries capital to start
