### ISSUE TITLE
Create a timer mode for quizzes

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#32]
As an AnyMemo user, I would like to be able to have a timer mode while doing a quiz where I have a maximum time of 30 seconds to answer a question on a flash card.

Tasks:

1. Create a button on the user interface to be able to go into quiz mode. (Task: #38)
2. Create mockup for UI (Task #78)
3. Create a timer. (Task: #39)
4. Display the timer on the UI. (Task: #40)
5. Keep track of the user's result for each question. (Task: #43)
6. Display the results once the quiz is completed. (Task: #46)
7. Write tests. (Task: #49)

Acceptance criteria:

- Code has been reviewed by someone other than the developer.
- All tests pass.
- Quality assurance has been preformed.

Risk: Low
Value: High
Story points: 8

**Comment by guipadua** [comment]
There is already a quiz mode. Check what is the difference of what is being added here (timer and results (?)). Maybe add future feature to see the trend of and how the user did over the time.

**Comment by guipadua** [comment]
Demoed, it worked. Espresso tests were done and they work locally only.
