### ISSUE TITLE
Integrate the continuous integration

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#7]
User story: #3 

Integrate the CI in the AnyMemo project. Ensure that when code is committed, the CI complies the application and that all tests are run.

**Comment by rekandiah** [comment]
hours spent: 3 days

**Comment by rekandiah** [comment]
Currently, Jenkins builds successfully on all our branches. However, it doesn't automatically check with every commit. There's a Github plugin that can be used but probably need to do more research on that. That is what I'm currently working on.

**Comment by coreylevine** [comment]
Here is a link to our wiki on how to run Jenkins: https://github.com/jameelbrochu/AnyMemo/wiki/Docker-and-Jenkins-commands-and-config-info

**Comment by j-suguma** [comment]
Helped with the process: 7 Hours

**Comment by jameelbrochu** [comment]
Ideal hours: 30 hours
