### ISSUE TITLE
Click twice to shuffle deck

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#73]
In order to shuffle the deck, currently, the user must click the shuffle button, go back to the homepage, and then click again on the shuffle button.

Then run the deck in the default order once again, you must click on the deck, go back to the homepage, and then click again on the list.

**Comment by rekandiah** [comment]
![shuffle](https://user-images.githubusercontent.com/15826622/37178095-7232af28-22ef-11e8-921f-e8050c441907.PNG)

**Comment by rekandiah** [comment]
number of hours: 3
