### ISSUE TITLE
Design for Hints

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#77]
User story: #26 

Create the design for what the frontend should look like for hints in the deck.
Ideal Hours: 2

**Comment by j-suguma** [comment]
Here is the rough sketch of how the UI will look like for the hint feature: 
![28217805_1976413912399521_1971552978_o](https://user-images.githubusercontent.com/25251601/36392815-eed3258a-157a-11e8-9327-b4ec53e60224.jpg)

**Comment by j-suguma** [comment]
This is the digital mock-up that was then created:
![shuffle mockup - page 3](https://user-images.githubusercontent.com/25251601/36392827-035255d0-157b-11e8-87bd-60d0da0e511c.png)

**Comment by j-suguma** [comment]
And here is a link to an interactive prototype. Click on the "English.db" to begin the interaction:
https://invis.io/WNFWQVQFDQ9
