### ISSUE TITLE
Design for Timer

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#78]
User story: #32 

Create the design for adding a timer to quiz mode.
Ideal Hours: 2

**Comment by j-suguma** [comment]
Here is the rough sketch of how the UI will look like for the timer mode feature:
![28208418_1976414005732845_1452481898_o](https://user-images.githubusercontent.com/25251601/36392875-44c7aa4c-157b-11e8-98cb-aea79df8d373.jpg)

**Comment by j-suguma** [comment]
This is the digital mock-up that was then created:
![shuffle mockup - page 4](https://user-images.githubusercontent.com/25251601/36392882-4de98104-157b-11e8-9665-60250c577a53.jpeg)

**Comment by j-suguma** [comment]
And here is a link to an interactive prototype. Click on the "More" on the same row as "English.db" to begin the interaction:
https://invis.io/WNFWQVQFDQ9
