### ISSUE TITLE
Split Jenkins in two separate tasks

### ISSUE THREAD

**Issue by mukulikadey** [jameelbrochu/AnyMemo#80]
As a developer, I would like to split Jenkins in two separate tasks: 
1. One for compilation and building
2. Other for running the tests

Acceptance Criteria:
1. All tests pass

Risk: Low
Priority: Low
Story points: 1

We assigned this user story low risk, low value and only one story point because our Jenkins currently functions properly. This would just be an enhancement to our already functioning continuous integration.

**Comment by j-suguma** [comment]
After some research, the CI pipeline is now split into two: 
One for having the compilation/build be successful
another one for the tests.
The way it works is the first "project" is just for the build and if it is successful it will trigger the next one which runs the tests.

**Comment by guipadua** [comment]
Since I can't access your jenkins, can you attach a screenshot of this? Thanks!

**Comment by mukulikadey** [comment]
Successful Build: 
![image](https://user-images.githubusercontent.com/25259429/37927592-8dfa0fa4-3108-11e8-97da-60c59258f536.png)

Tests for the build above:
![image](https://user-images.githubusercontent.com/25259429/37927641-ac8514b4-3108-11e8-8685-1fd5d27d5292.png)

Build failing and tests not being triggered:
![image](https://user-images.githubusercontent.com/25259429/37927677-c084b4ba-3108-11e8-9a79-3ce42461f7a9.png)

@guipadua is this good?

**Comment by guipadua** [comment]
I saw that on your report, I think there is another high level visualization. Let's check when we meet today.
