### ISSUE TITLE
Ability to change the background color of the screen

### ISSUE THREAD

**Issue by mukulikadey** [jameelbrochu/AnyMemo#81]
As a user, I should be able to change the background color of the screen. 

Tasks: 

Acceptance criteria:
1. Code has been reviewed by two people.
2. All tests pass.
3. Quality assurance has been preformed.

Risk: 
Priority: 
Story points:

**Comment by coreylevine** [comment]
We decided not to implement this feature. We will consider implementing it in the future if we continue to work on this project.
