### ISSUE TITLE
Keep track of the quiz results history

### ISSUE THREAD

**Issue by mukulikadey** [jameelbrochu/AnyMemo#82]
As a user, I should be able to see my past 10 quiz marks for each quiz.

Tasks: 
1. Create a new database for storing the quiz history. (Task #141)
2. Create a new history entity, dao and daoImpl. (Task #142)
3. Create a table in the new database called history. (Task #143)
4. Create mockups. (Task #144)
5. Create an XML for the history page. (Task #145)
6. Create a new activity to launch the history page. (Task #146)

Acceptance criteria:
1. Code has been reviewed by two people.
2. All tests pass.
3. Quality assurance has been preformed.

Risk: Low
Priority: High
Story points: 8

This story is assigned 8 story points because a new database, entity, dao, xml and activity must be added. Since we have experience creating these things, this user story is 8 story points as opposed to 13 story points. A significant amount of work must still be done.

[Unit Test 1](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/HistoryDaoTest.java)

[Unit Test 2](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/functionality/testHistoryFunctions.java)

[Espresso Test](https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/QuizHistoryTest.java)

![image](https://user-images.githubusercontent.com/25251601/38701440-da00c3e6-3e6b-11e8-88d3-26c0d9c16c9c.png)

**Comment by coreylevine** [comment]
Final Mockup:

![image](https://user-images.githubusercontent.com/25109164/38529069-bd219d1e-3c30-11e8-8e3f-ebee838b1411.png)

**Comment by j-suguma** [comment]
![image](https://user-images.githubusercontent.com/25251601/38701536-224404ba-3e6c-11e8-83ae-ed9f0407e77a.png)

**Comment by mukulikadey** [comment]
UNIT TESTS: 
1. https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/db/HistoryDaoTest.java

2. https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/functionality/testHistoryFunctions.java

ESPRESSO TESTS: 
https://github.com/jameelbrochu/AnyMemo/blob/master/app/src/androidTest/java/org/liberty/android/fantastischmemo/test/ui/QuizHistoryTest.java

**Comment by guipadua** [comment]
Demoed and it works. It persists on the database. Has all types of tests. There is a message for when it was not run yet. Didn't test for that yet.
