### ISSUE TITLE
Toggle Hint

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#86]
As an AnyMemo user, I would like to be able to turn the hint mode on and off.

Tasks:
1. Create a toggle checkbox for hint mode on and off. (Task: #89 )
2. Make the logic for displaying either both hint/answer or just answer based on selection. (Task: #90)
3. The XML for settings, change the text for change (font size, ...) for hint and answer. (Task: #91)
4. Write espresso tests. (Task: #92) 

Acceptance criteria:
- Code has been reviewed by two people.
- All tests pass.
- Quality assurance has been preformed.

Risk: Medium
Priority: High
Story points: 5

Acceptance Tests:
![hint](https://user-images.githubusercontent.com/15826622/37178810-99670e84-22f1-11e8-8bb9-6dfc2eb72c13.PNG)

This story is 5 points because the hint logic has already been implemented, but we still need to write the logic for the toggle, and modify the XML files as well.

**Comment by mukulikadey** [comment]
![image](https://user-images.githubusercontent.com/25259429/37569933-c52693fc-2abf-11e8-958c-8d09f7a02723.png)

Acceptance test PASSED for the Hint Toggle Feature.

**Comment by coreylevine** [comment]
Demo video for Sprint 4 virtual release meeting:
https://drive.google.com/open?id=1juZm6Akyg-kF64sRkUhTF7MYkcivuasF

**Comment by guipadua** [comment]
Based on the video looks fine. Maybe a bit hard to get too, but I guess that's where all options are located anyway.

**Comment by mukulikadey** [comment]
@guipadua Yes, I agree, but like you said, since the settings included all the options to configure the cards, I wanted to keep it consistent with what the app had already, thus I placed it in that location.

**Comment by mukulikadey** [comment]
Actual hour(s): 15
