### ISSUE TITLE
Create detailed results page to review quiz

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#87]
As an AnyMemo user, after having completed my quiz, I would like to review the questions to see which ones I got right and which ones I got wrong.

Tasks:
1. Create mockup for UI of detailed results page. (Task #93)
2. Add a review button after the user has completed a quiz. (Task #94)
3. Keep track of the user's result for each individual question. (Task #95)
4. Create an activity to display the results for each question once the quiz is completed. (Task #96)
5. Write tests (done when implementing methods)

Acceptance criteria:
- Code has been reviewed by two people.
- All tests pass.
- Quality assurance has been preformed.

Risk: Low
Priority: Medium
Story points: 5

Acceptance Tests:

![review](https://user-images.githubusercontent.com/15826622/37178910-e0d33072-22f1-11e8-8e45-5cabf54f5ee9.PNG)

This user story is 5 points because a brand new activity must be created and data must be stored into ArrayLists, and then we must pass them from one activity to another. Creating a new button is relatively easy since we can copy the logic of the other buttons already on the dialog.

**Comment by coreylevine** [comment]
Demo video for Sprint 4 virtual release meeting:
https://drive.google.com/open?id=1CYYSgUirnt5t2xSHm7rQi2-f6QVVSU4p

**Comment by jameelbrochu** [comment]
![image](https://user-images.githubusercontent.com/16848284/37577068-1b4d98b6-2b06-11e8-8a05-a31d7ad62dd7.png)
Acceptance tests for Detailed Results Page feature.

**Comment by rekandiah** [comment]
number of hours: 3

**Comment by guipadua** [comment]
Based on the video looks fine. And I guess it doesn't make sense to edit this information. A possible question/enhancement: will it be stored anywhere for a trend over time?
Just a comment/thought: If the user got right or wrong is up to their own decision, right? It's not the app judging, but the user himself.

**Comment by jameelbrochu** [comment]
@guipadua In fact, keeping the history of the user's quiz results is an enhancement we have planned already for a future sprint (#82). And yes, it is the user who is telling the app if they got it right or wrong.

**Comment by rekandiah** [comment]
THIS USER STORY IS MANUALLY TESTED
