### ISSUE TITLE
Change Timer Color and Add Countdown Sound

### ISSUE THREAD

**Issue by coreylevine** [jameelbrochu/AnyMemo#88]
As an AnyMemo user, I would like the timer to change colours to red when there is 10 seconds left in the quiz.

When there is 5 seconds left, I would like a countdown sound to start.

Story Points: 1

Originally, when we thought of this feature we thought it would be difficult. However, after looking into the code we realized that it was simple. As such, this story is assigned only one story point.

Ideal hours: 0.5

Acceptance Tests:

![red](https://user-images.githubusercontent.com/15826622/37178974-1bb3ac1c-22f2-11e8-87e6-078533314658.PNG)

**Comment by j-suguma** [comment]
![image](https://user-images.githubusercontent.com/25251601/38167915-35d942c8-350d-11e8-8660-4a3353997aba.png)

**Comment by mukulikadey** [comment]
Virtual Release Video: 

[TimerSoundColor.zip](https://github.com/jameelbrochu/AnyMemo/files/1866778/TimerSoundColor.zip)

**Comment by mukulikadey** [comment]
Class Diagram: https://github.com/jameelbrochu/AnyMemo/wiki/Class-Diagram

**Comment by guipadua** [comment]
Video looks good. Are there other tests besides the acceptance tests added?

**Comment by coreylevine** [comment]
@guipadua Currently there are not. We are having trouble running espresso tests for the quiz activity. For now, we have updated our PR policy to manually test this feature with every pull request to ensure it functions properly.

**Comment by coreylevine** [comment]
Final mockup of timer color feature:
![image](https://user-images.githubusercontent.com/25109164/38695541-90848aec-3e5a-11e8-9ff5-49015750fbe6.png)

**Comment by rekandiah** [comment]
THIS USER STORY IS MANUALLY TESTED
