### ISSUE TITLE
Create mockup for detailed results page

### ISSUE THREAD

**Issue by jameelbrochu** [jameelbrochu/AnyMemo#93]
User story: #87 

Create a mockup of UI design for the new detailed results page.
Ideal Hour(s): 3

**Comment by jameelbrochu** [comment]
![91b23a33-a4e6-4dda-8ffa-1885a423da8e](https://user-images.githubusercontent.com/16848284/37486457-e944bc76-2864-11e8-9839-01fc01a5b885.jpeg)

**Comment by coreylevine** [comment]
This mockup looks good! I like how now you can see exactly which questions you got right and which ones you got wrong on a quiz.

In your mockup, it says question 1, question 2... Will you be displaying the actual question from the quiz, or will you just be writing question 1, question 2...

**Comment by jameelbrochu** [comment]
Since there is no character limit for the questions, it would get too long to have the actual question displayed on the screen.

**Comment by coreylevine** [comment]
Maybe as an enhancement we can click on the question and then a popup will appear with the question.

**Comment by jameelbrochu** [comment]
We could also have the correct answer displayed on the detailed results page as another enhancement, in addition to the popup displaying the question.
